// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TurnBasedStrategyCore","status":true,"description":"Core changes for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategyStats","status":true,"description":"Stats and class parameters handling for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategyWindows","status":true,"description":"Window and menu handling for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategyScene","status":true,"description":"Scene handling for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategyObjects","status":true,"description":"Object handling for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategySprites","status":true,"description":"Sprite objects for a turn based strategy game","parameters":{}},
{"name":"TurnBasedStrategyManagers","status":true,"description":"Manager objects for a turn based strategy game","parameters":{}}
];
